var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/register/by-form/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e1f8061d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ef111e68._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_c821e33c._.js")
R.c("server/chunks/ssr/node_modules_next_a12186a1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__543eb079._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_register_by-form_page_actions_1352f3df.js")
R.m(98824)
module.exports=R.m(98824).exports
