var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/profile/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__d7c66014._.js")
R.c("server/chunks/ssr/_28132304._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ef111e68._.js")
R.c("server/chunks/ssr/_54c2aae7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/node_modules_next_446e7587._.js")
R.c("server/chunks/ssr/[root-of-the-server]__543eb079._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_ee586517._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_profile_page_actions_a2e720cb.js")
R.m(22505)
module.exports=R.m(22505).exports
