import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/authConfig";
import { AppSessionProvider } from "./_components/app-session-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session: any = null;

  try {
    session = await auth();
  } catch (error) {
    console.error("[layout] auth() error", error);
    session = null;
  }
  let userName: string | null = null;

  const rawProfile = (session?.user as any)?.profile as string | undefined;

  if (rawProfile) {
    try {
      const profile = JSON.parse(rawProfile) as any;
      const titleTh = profile?.title_th ?? '';
      const firstTh = profile?.firstname_th ?? '';
      const lastTh = profile?.lastname_th ?? '';
      const nameTh = profile?.name_th ?? '';

      const fullNameParts = [
        `${titleTh}${firstTh}`.trim(),
        lastTh,
      ].filter(Boolean);

      const fullName =
        fullNameParts.length > 0
          ? fullNameParts.join(' ').trim()
          : nameTh;

      userName = fullName || null;
    } catch {
      userName = null;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppSessionProvider userName={userName}>{children}</AppSessionProvider>
      </body>
    </html>
  );
}
